
services:
 
    build: 
    environment:
      API_ID: $API_ID  
      API_HASH: $API_HASH  
      BOT_TOKEN: $BOT_TOKEN
      APP_NAME : $APP_NAME
      BIN_CHANNEL : $BIN_CHANNEL
      DATABASE_URL : $DATABASE_URL
      ENV : $ENV
      NO_PORT : $NO_PORT
      OWNER_ID : $OWNER_ID
      UPDATES_CHANNEL : $UPDATES_CHANNEL
